"""The async command base class.

Design lineage
--------------
Borrowed from Cowrie's ``HoneyPotCommand``: every emulated command is a class
with a small, uniform contract (write output, read input, report an exit
status). We keep that shape but make it ``async`` so it composes with
asyncio/asyncssh, and we replace Cowrie's manual ``cmdstack`` with the natural
coroutine call stack — an interactive command simply ``await``\\s
:meth:`read_line` and blocks the shell until its ``run`` returns.

Contract
--------
The interpreter resolves a command token to a ``Command`` subclass, then::

    cmd = SubCls(ctx, argv, stdin, stdout, stderr)
    exit_code = await cmd.run()

* ``argv`` is the command as invoked; ``argv[0]`` is the token the attacker
  typed (``ls`` or ``/bin/ls``), and :pyattr:`args` is everything after it.
* ``run`` returns an ``int`` exit code. Subclasses override ``run`` only.
* Output goes through :meth:`write`/:meth:`line` (stdout) and
  :meth:`error`/:meth:`errline` (stderr); the interpreter/pipeline decides
  where those streams actually go.
"""

from __future__ import annotations

from honeyshell.commands.context import ShellContext
from honeyshell.commands.streams import (
    NullReader,
    Readable,
    StringWriter,
    Writable,
)

__all__ = ["Command", "DeferToLLM"]


class DeferToLLM(Exception):
    """A registered command raises this to hand its invocation to the LLM seam.

    Design lineage (HANDOFF v5, "做法 B"): the registry/miss_handler split
    normally means *hit* commands (those with a registered class) never reach
    the LLM. But some builtins can only faithfully handle a *subset* of their
    real behaviour — ``awk`` covers the common ``{print $N}`` field-extraction
    idiom deterministically, yet complex programs (``/pattern/``, ``BEGIN``,
    arithmetic) are rare and better generated by the model than faked.

    Rather than emit a misleading ``hit=True`` while secretly calling the LLM
    (which would corrupt the miss-rate metric that the whole report hinges on,
    see HANDOFF §21/§32), such a command raises ``DeferToLLM``. The interpreter
    catches it, re-classifies the command as a genuine miss (``hit=False`` in
    the audit stream), and routes it through the normal ``miss_handler``. If no
    LLM backend is wired, the interpreter falls back to the command's own
    conservative output via :meth:`Command.fallback` so the honeypot never
    crashes and never exposes itself with a bogus error.

    This keeps three things honest at once: the hit/miss statistic (deferred
    commands count as miss), the security model (the LLM path is the single
    seam), and resilience (a no-LLM deployment still answers plausibly). The
    mechanism is reusable — a future complex ``sed``/``grep`` can defer too.
    """


class Command:
    #: Canonical name; set automatically by @register if left blank.
    name: str = ""

    def __init__(
        self,
        ctx: ShellContext,
        argv: list[str],
        stdin: Readable | None = None,
        stdout: Writable | None = None,
        stderr: Writable | None = None,
    ) -> None:
        self.ctx = ctx
        self.argv = list(argv)
        self.stdin: Readable = stdin or NullReader()
        self.stdout: Writable = stdout or StringWriter()
        self.stderr: Writable = stderr or StringWriter()
        self.exit_code = 0

    # -- convenience accessors --

    @property
    def prog(self) -> str:
        """The token as invoked (argv[0]), for use in error messages."""
        return self.argv[0] if self.argv else self.name

    @property
    def args(self) -> list[str]:
        """Everything after argv[0]."""
        return self.argv[1:]

    # -- output helpers --

    def write(self, data: str) -> None:
        self.stdout.write(data)

    def line(self, data: str = "") -> None:
        self.stdout.write(data + "\n")

    def error(self, data: str) -> None:
        self.stderr.write(data)

    def errline(self, data: str = "") -> None:
        self.stderr.write(data + "\n")

    def fail(self, message: str, code: int = 1) -> int:
        """Write ``prog: message`` to stderr and return an exit code."""
        self.errline(f"{self.prog}: {message}")
        return code

    # -- input helpers --

    async def read_line(self) -> str | None:
        return await self.stdin.readline()

    async def read_all(self) -> str:
        return await self.stdin.read()

    # -- to override --

    async def run(self) -> int:
        raise NotImplementedError

    async def fallback(self) -> int:
        """Conservative output used when the command raised :class:`DeferToLLM`
        but no LLM backend is available.

        The interpreter calls this instead of the miss_handler when it has no
        way to reach the model. The default succeeds silently (exit 0, no
        output) — for a deferred command, staying quiet is safer than emitting a
        ``command not found`` (the binary provably exists) or a fabricated error
        that could fingerprint the honeypot. Subclasses may override to return
        something more plausible (e.g. awk echoing whole lines like ``$0``).
        """
        return 0
